hereversion: '3.8'

services:
  # The Public Entry Point
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    env_file: .env 
    environment:
      # Injects the secret for JWT verification
      - JWT_SECRET=${API_GATEWAY_JWT_SECRET} 
    networks:
      - medic_network

  # The Learning Microservice
  education-service:
    build: ./education-service
    ports:
      - "3002" # Internal port only
    networks:
      - medic_network

  # Frontend is usually simple
  keto-frontend:
    build: ./keto-frontend 
    ports:
      - "80:80"
    networks:
      - medic_network

networks:
  medic_network:
    driver: bridge
